apiVersion: v1
kind: Secret
metadata:
  name: blog-mysql-secret
  namespace: blog-platform
type: Opaque
stringData:
  root-password: "RootPass123"
  database: "blog_db"
  user: "blog_user"
  password: "BlogPass123"
